version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: consumoreal_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: consumoreal
    ports:
      - "5435:5432"
    volumes:
      - postgres_consumoreal_data:/var/lib/postgresql/data

volumes:
  postgres_consumoreal_data: